apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert-tls
  namespace: openshift-config
spec:
  secretName: api-cert-tls
  duration: 2160h0m0s
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Camptocamp
  commonName: {{ .Values.apiURL | quote }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.apiURL | quote }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io