apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard-tls
  namespace: openshift-ingress
spec:
  secretName: apps-wildcard-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Camptocamp
  commonName: {{ .Values.wildcardDomain }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.wildcardDomain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io