{{- range .Values.wildcardDomains }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard-tls
  namespace: openshift-ingress
spec:
  secretName: apps-wildcard-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - Camptocamp
  commonName: {{ . | quote }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ . | quote }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}